package ir.ramtung.tinyme.domain.entity;

public enum MatchingOutcome {
    OK,
    QUEUED_DURING_AUCTION_STATE,
    NOT_ACTIVATABLE,
    NOT_ENOUGH_CREDIT,
    NOT_ENOUGH_POSITIONS,
    MINIMUM_QUANTITY_NOT_SATISFIED,
    NOT_EQUAL_MINIMUM_EXECUTION_QUANTITY
}
